name: Deploy to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Save private key to a file
        echo "${PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem

        # SCP the JAR file to EC2
        scp -i private_key.pem target/AccountBot-0.0.1-SNAPSHOT.jar ubuntu@ec2-54-248-138-109.ap-northeast-1.compute.amazonaws.com:~

        # SSH to EC2 and run deployment commands
        ssh -i private_key.pem ubuntu@ec2-54-248-138-109.ap-northeast-1.compute.amazonaws.com << 'EOF'
          PORT=8080
          PID=$(lsof -ti:$PORT)
          if [ -n "$PID" ]; then
            kill -9 $PID
          fi
          rm app.log
          nohup java -jar ~/AccountBot-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
       
